--- #YAML:1.0
name:               Acme-CorpusScrambler
version:            0.03
abstract:           An Acme way doing Lorem Ipsum.
author:
    - shelling, <navyblueshellingford@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::All:              0
    Test::More:           0
    Text::Greeking::zh_TW:  0.0.3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
