--- 
author: Kang-min Liu, <gugod@gugod.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Acme::CorpusScrambler
name: Acme-CorpusScrambler
no_index: 
  directory: 
    - inc
    - t
requires: 
  IO::All: 0
  Test::More: 0
  Text::Greeking::zh_TW: 0.0.3
version: 0.01
